services:
  fhir:
    image: intersystemsdc/irishealth-community:latest
    ports:
      - "52775:52773"
      - "1974:1972"

  iris:
    build: .
    image: smart-patient-summary:latest
    ports:
      - "52774:52773"
      - "1973:1972"
    volumes:
      - ./keys:/external/keys
    command: -k /external/keys/iris-container-x64.key
    environment:
      - FHIR_BASE_URL=http://fhir:52773/fhir/r4
      - FHIR_BASIC_USER=_SYSTEM
      - FHIR_BASIC_PASS=SYS
    depends_on:
      - fhir
